# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3425b70e74588d28801a0474396fd98e1d2ec1777dbebb18fd1c34a367cdc8e78371d02ab1bb30207766ce2524cfdc7f554acaa39bd70fbed7537d2dbd7d356a

test:
  secret_key_base: 71b842a69d35116607728d68bf788c3d12693c0d025ccf51ac515a812fab4b97d49630fb0c7dba3aefda471954d0bb0afe1efd90ebafea5c7988051f09141b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
